---
- name: Deploy Symphony on Kubernetes locally
  hosts: appserver
  become: true

  tasks:
    - name: Ensure kubectl is installed
      apt:
        name: kubectl
        state: present
        update_cache: yes

    - name: Apply Kubernetes manifest
      command: kubectl apply -f /home/admin/symphony/k8s/symphony.yaml --validate=false
      environment:  
        KUBECONFIG: /home/admin/.kube/config

