apiVersion: apps/v1
kind: Deployment
metadata:
  name: symphony
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symphony
  template:
    metadata:
      labels:
        app: symphony
    spec:
      containers:
      - name: symphony
        image: bluesboynix/symphony:latest   # <-- your Docker Hub image
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: symphony-service
spec:
  type: NodePort
  selector:
    app: symphony
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080   # fixed NodePort

